description: Copies remote branch and creates local


inputs:
  remote_repo:
    description: Remote source project
    required: true

  remote_branch:
    description: Remote source branch
    required: false
    default: main

  target_branch:
    description: Local target branch
    required: false
    default: upstream

  auto:
    description: Automatic handling
    required: false
    default: ''

  token:
    description: Github token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - if: inputs.auto != ''
      uses: li1ht2ay-3es/gi1-ac2io3s@user-action



    - if: inputs.auto != ''
      uses: li1ht2ay-3es/gi1-ac2io3s@checkout-branch
      with:
        token: ${{ inputs.token }}



    - shell: bash
      run: |
        git remote add remote "https://github.com/${{ inputs.remote_repo }}.git"

        git fetch remote ${{ inputs.remote_branch }}
        git -c advice.detachedHead=false checkout remote/${{ inputs.remote_branch }}



    - shell: bash
      run: |
        if [[ "${{ inputs.target_branch }}" == "" ]]; then
          branch="upstream"
        else
          branch=${{ inputs.target_branch }}
        fi


        #########


        git checkout -B $branch
        git push -f origin HEAD:$branch
