description: Changes last commit message


inputs:
  author:
    description: Commit author
    required: false
    default: ''

  email:
    description: Commit email
    required: false
    default: ''

  title:
    description: Message title
    required: false
    default: ''

  body1:
    description: First line
    required: false
    default: "\n"

  body2:
    description: Second line
    required: false
    default: "\n"

  body3:
    description: Third line
    required: false
    default: "\n"

  body4:
    description: Fourth line
    required: false
    default: "\n"

  body5:
    description: Fifth line
    required: false
    default: "\n"

  auto:
    description: Automatic handling
    required: false
    default: ''

  token:
    description: Github token
    required: false
    default: ''

  branch:
    description: Target branch
    required: false
    default: ''


runs:
  using: composite

  steps:
    - if: inputs.auto != ''
      uses: fu1ny2t-3es/gi1-ac2io3s@user-action



    - if: inputs.auto != ''
      uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}



    - shell: bash
      run: |
        git fetch --deepen=1 origin ${{ github.github_ref_name }}
        git reset --hard



    - shell: bash
      run: |
        if [[ -n "${{ inputs.title }}" ]]; then
          msg=$(printf "%s\n\n%s\n%s\n%s\n%s\n%s\n" \
            '${{ inputs.title }}' \
            '${{ inputs.body1 }}' \
            '${{ inputs.body2 }}' \
            '${{ inputs.body3 }}' \
            '${{ inputs.body4 }}' \
            '${{ inputs.body5 }}' \
          )
          git commit --amend -m "$msg"
        fi



    - shell: bash
      run: |
        if [[ -n "${{ inputs.author }}" ]]; then
          git commit --amend --author="${{ inputs.author }} <${{ inputs.email }}>" --no-edit
        fi



    - if: inputs.auto != ''
      shell: bash
      run: |
        git push -f origin
