on:
  # push:
  workflow_dispatch:


jobs:

  checkout-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
        with:
          branch: ${{ inputs.branch }}

          auto: true
          token: ${{ secrets.token }}
