on:
  # push:
  workflow_dispatch:


jobs:

  amend-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/gi1-ac2io3s@amend-repo
        with:
          auto: true
          token: ${{ secrets.token }}
