on:
  # push:


env:
  message: ""


jobs:

  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
          # ref: my-branch


      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git reset --hard HEAD~1

          git commit --amend -m "${{ env.message }}"

          git push -f origin

        shell: bash
