on:
  # push:


env:
  squash: 1


jobs:

  squash:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: ${{ env.squash }}+2
          # ref: my-branch


      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git reset --hard HEAD~1

          git reset --soft HEAD~${{ env.squash }}
          git commit --amend --no-edit

          git push -f origin

        shell: bash
